version: '3.8'

services:
  db:
    image: postgres:16
    container_name: personal_blog_postgres  
    restart: always
    environment:
      POSTGRES_USER: ghostmaga
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: personal_blog
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
